server:
  port: 8088

debug : false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.backendboard: debug
    org.springframework.web.servlet : debug
    org.hibernate.type.descriptor.sql.BasicBinder : trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username : postgres
    password : 1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mvc.hiddenmethod.filter.enabled: true
  sql.init.mode : always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

---
spring:
  config.activate.on-profile: cloud-type
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  sql.init.mode: always
